stages:
  - name: warmup-random
    duration_timesteps: 200000
    opponent_player:
      id: random

  - name: midgame-max-power
    duration_timesteps: 400000
    opponent_player:
      id: max-power

  - name: final-heuristic
    opponent_player:
      id: heuristic
